### ISSUE TITLE
Attribute style for key access makes object properties fail

### ISSUE THREAD

**Issue by ocurero** [mdatapipe/dinterpol#2]
Hi there,

First all, great library, just what I needed!!

Making attribute style for key access is nice but this feature prevents for using object properties. Take the following example:

```
from datetime import datetime
from dinterpol import Template
Template({'today is': '{now.day}'}).render({'now': datetime.now()})
```

I get:
```

  container[key] = eval(f_string_code, mapping)
  File "Expression: "now["day"]"", line 1, in <module>
TypeError: 'datetime.datetime' object is not subscriptable
```

Would be nice if it fallback to the original format (so things that are not a dictionary would work) or at least an option in render function would switch the way it works.

**Comment by joaompinto** [comment]
Hello,
would it work for you to have a flag on Template() to disable the attribute conversion behavior ?

Thanks

**Comment by ocurero** [comment]
Hi,

Yeah, that would be cool too!

Thanks!

**Comment by joaompinto** [comment]
Hello,
thanks for the suggestion, with the new version you can now use:
`Template({'today is': '{now.day}'}, False).render({'now': datetime.now()})`
